version: "3"
services:
    database:
        image: mysql:latest
        container_name: hsh-database-dev
        hostname: hsh-database-dev
        volumes:
            - db-data:/var/lib/mysql
        env_file:
            - ./containers/databases/.env
        ports:
            - "3306:3306"
        networks:
            - hsh-network

    application:
        build: ./containers/php
        container_name: hsh-application-dev
        hostname: hsh-application-dev
        working_dir: /var/www/html
        depends_on:
            - database
        volumes:
            - ./application:/var/www/html
        networks:
            - hsh-network

    webserver:
        build: ./containers/nginx
        container_name: hsh-webserver-dev
        hostname: hsh-webserver-dev
        depends_on:
            - application
        volumes:
            - ./application:/var/www/html
        ports:
            - "80:80"
        networks:
            - hsh-network

volumes:
    db-data:

networks:
    hsh-network:
        driver: bridge
